### ISSUE TITLE
经验点模式下扣除有误

### ISSUE THREAD

**Issue by Miyazono2003** [0XPYEX0/FlyWithFood#12]
插件扣除经验值貌似是按照百分比来扣除的，这样导致1000级和1级的消耗速度一样快，建议改成扣除指定经验值（？等级越高消耗速度越慢比较合理吧（（

**Comment by 0XPYEX0** [comment]
我本来就是设计成你说的那样
奈何Bukkit和Sponge都不提供经验值的get和set  ，只提供了经验等级的get和set
无奈 我只能用百分比的方式实现
走nms的话 兼容性骤降 狠狠爆炸
所以捏 我没有办法做 臣妾做不到啊  :((((

**Comment by 0XPYEX0** [comment]
你要是还有问题 可以加我QQ 咱来私下击剑🤺

**Comment by 0XPYEX0** [comment]
貌似找到了可行的方法
等待测试

**Comment by 0XPYEX0** [comment]
试了一下，需要特殊的方法才可以，Bukkit本身的方法依然有问题。等待研究

**Comment by 0XPYEX0** [comment]
已修复
